---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: Cloud Manager和Cloud Volumes ONTAP 功能不一的詳細資料、可協助您管理系統。 
---
= 預設組態
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager和Cloud Volumes ONTAP 功能不一的詳細資料、可協助您管理系統。



== Linux上Cloud Manager的預設組態

如果您需要疑難排解Cloud Manager或Linux主機、可能有助於瞭解Cloud Manager的設定方式。

* 如果您是從NetApp Cloud Central（或直接從AWS Marketplace或Azure Marketplace）部署Cloud Manager、請注意下列事項：
+
** 在 AWS 中、 EC2 Linux 執行個體的使用者名稱為 EC2-user.
** 無論是AWS或Azure、Cloud Manager映像的作業系統都是Red Hat Enterprise Linux 7.4（HVM）。
+
作業系統不含 GUI 。您必須使用終端機來存取系統。



* Cloud Manager安裝資料夾位於下列位置：
+
/opt/application/NetApp/cloudmanager

* 記錄檔包含在下列資料夾中：
+
/opp/application/NetApp/cloudmanager/log

* Cloud Manager 服務的名稱為 occm 。
* occm 服務取決於 MySQL 服務。
+
如果 MySQL 服務當機、則 occm 服務也會停機。

* Cloud Manager 會在 Linux 主機上安裝下列套件（如果尚未安裝）：
+
** 7Zip
** AWSCLI
** Java
** Kubecl
** MySQL
** Tridentctl
** WGet






== 的預設組態 Cloud Volumes ONTAP

瞭解 Cloud Volumes ONTAP 根據預設設定的功能可協助您設定及管理系統、尤其是熟悉 ONTAP 使用功能時、因為 Cloud Volumes ONTAP 預設的功能與 ONTAP 使用功能不相同、所以使用功能不一。

* 在AWS和Azure中、可用的是單節點系統和HA配對。Cloud Volumes ONTAP
* Cloud Manager部署Cloud Volumes ONTAP 時會建立一個資料服務SVM、雖然您可以從System Manager或CLI建立另一個資料服務SVM、但不支援使用多個資料服務SVM。
* 預設會建立多個網路介面：
+
** 叢集管理 LIF
** 叢集間 LIF
** 節點管理 LIF
** iSCSI 資料 LIF
** CIFS 與 NFS 資料 LIF
+

NOTE: 由於 Cloud Volumes ONTAP EC2 需求、 LIF 容錯移轉功能預設為停用。將 LIF 移轉至其他連接埠會中斷執行個體上 IP 位址與網路介面的外部對應、使 LIF 無法存取。



* 使用HTTPS將組態備份傳送至Cloud Manager。Cloud Volumes ONTAP
* 登入Cloud Manager後、即可從存取備份 https://ipaddress/occm/offboxconfig/[]
* Cloud Manager 設定的磁碟區屬性與其他管理工具（例如 System Manager 或 CLI ）有所不同。
+
下表列出 Cloud Manager 設定的 Volume 屬性與預設值不同：

+
[cols="15,85"]
|===
| 屬性 | Cloud Manager 設定的價值 


| 自動調整大小模式 | 成長 


| 最大自動調整大小  a| 
1 、 000 %


NOTE: Cloud Manager管理員可從「設定」頁面修改此值。



| 安全風格 | 適用於 CIFS Volume UNIX for NFS Volume 的 NTFS 


| 空間保證風格 | 無 


| UNIX 權限（僅限 NFS ） | 777 
|===
+
有關這些屬性的信息，請參見 _volume creation_ 手冊頁。





== 開機和root資料Cloud Volumes ONTAP 以供使用

除了儲存使用者資料之外、Cloud Manager也會購買雲端儲存設備、以便在每Cloud Volumes ONTAP 個作業系統上開機和取得根資料。



=== AWS

* 一個提供IOPS SSD磁碟以供Cloud Volumes ONTAP 執行效能不整的開機資料、約為45 GB和1、250 PIOPS
* 一個通用SSD磁碟、用於Cloud Volumes ONTAP 提供約140 GB的資料以供參考
* 每個開機磁碟和根磁碟各一份 EBS 快照


在HA配對中、Cloud Volumes ONTAP 兩個支援節點都會將其根磁碟複寫到合作夥伴節點。



=== Azure

* 一個Premium Storage SSD磁碟用於Cloud Volumes ONTAP 提供約73 GB的可靠開機資料
* 一個Premium Storage SSD磁碟、用於Cloud Volumes ONTAP 提供約140 GB的資料
* 每個開機磁碟和根磁碟各一份 Azure 快照




=== 磁碟所在位置

Cloud Manager從AWS和Azure中佈建儲存設備、如下所示：

* 開機資料位於連接至EC2執行個體或Azure虛擬機器的磁碟上。
+
此磁碟包含開機映像、 Cloud Volumes ONTAP 不適用於 Image.

* 根資料包含系統組態和記錄檔、位於 aggr0 中。
* 儲存虛擬機器（ SVM ）根磁碟區位於 aggr1 中。
* 資料磁碟區也位於 aggr1 中。

