---
sidebar: sidebar 
permalink: task_launching_aws_mktp.html 
keywords: install, installation, installing, marketplace, aws, launch, launching, ec2 console 
summary: 最好使用NetApp Cloud Central在AWS中啟動Cloud Manager、但您可以視需要從AWS Marketplace啟動。 
---
= 從AWS Marketplace啟動Cloud Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
最好使用AWS啟動Cloud Manager https://["NetApp Cloud Central"^]、但您可以視需要從AWS Marketplace啟動。


TIP: 如果您從AWS Marketplace啟動Cloud Manager、Cloud Manager仍會與NetApp Cloud Central整合。 link:concept_cloud_central.html["深入瞭解整合"]。

.關於這項工作
下列步驟說明如何從EC2主控台啟動執行個體、因為主控台可讓您將IAM角色附加至Cloud Manager執行個體。這無法使用「按一下」選項。

.步驟
. 為 EC2 執行個體建立 IAM 原則和角色：
+
.. 請從下列位置下載 Cloud Manager IAM 原則：
+
https://["NetApp OnCommand 解決方案Cloud Manager：AWS和Azure原則"^]

.. 從 IAM 主控台複製並貼上 Cloud Manager IAM 原則中的文字、以建立您自己的原則。
.. 建立角色類型為 Amazon EC2 的 IAM 角色、並將您在上一步建立的原則附加至角色。


. 前往 https://["AWS Marketplace 上的 Cloud Manager 頁面"^]。
. 按一下 * 繼續 * 。
. 在「自訂啟動」索引標籤上、針對您所在的地區按一下*「以EC2主控台啟動*」、然後選擇：
+
.. 視區域可用度而定、請選擇T3.medium（建議）、T2.medium或M4.large執行個體類型。
.. 選取符合您需求的VPC、子網路、IAM角色及其他組態選項。
.. 保留預設儲存選項。
.. 視需要輸入執行個體的標記。
.. 指定Cloud Manager執行個體所需的連線方法：SSH、HTTP和HTTPS。
.. 按一下 * 「 Launch * 」。




.結果
AWS 會以指定的設定啟動軟體。Cloud Manager執行個體和軟體應在大約五分鐘內執行。

.完成後
在網頁瀏覽器中輸入公有IP位址或私有IP位址、然後完成設定精靈、即可登入Cloud Manager。
